config/routes.rb
#require 'resque/server'

ORitmo::Application.routes.draw do

  get "accounts/create"
  get "accounts/update"
  get "transactions/create"
  get "payments/index"
  get "payments/confirm"
  get "payments/complete"
  get "termos" => 'pages#termos'
  get "upload" => 'products#upload'
  get "home" => 'pages#index'
  get "about-us" => 'pages#about_us', as: :about_us
  get "faq" => 'pages#faq', as: :faq
  get "sitemap" => 'pages#sitemap'

  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_for :admin_users


  resources :users do
    resources :videos
    resources :products

    resources :collections do
      get 'details'
    end

    get 'details'
    get 'edit_password'

    member do
      get 'edit_photo'
    end

    collection do
      get 'status'
      post 'update_photo'
      put 'update_password'
    end
  end

  get 'users(/:order_by)' => 'users#index'

  get 'set_currency/:currency' => 'users#set_currency', :as => :set_currency

  resources :products do
    get 'form'
    collection do
      get 'upload'
      post 'upload_callback'
    end
    resources :orders
    member do
      get 'create_sample'
      get 'download'
      get 'license'
    end
  end

  resources :seller_terms, :only => [:new,:create]
  resources :buyer_terms, :only => [:new,:create]

  resources :payments do
    member do
      get :confirm
      get :cancel
    end
    collection do
      get :withdraw
      get :exchange_rate
    end
  end

  get 'payments/purchase/:product_id' => 'payments#purchase', :as => :purchase_payment

  namespace :admin do
    resources :categories do
      collection do
        get 'roots'
      end
    end
    resources :rhythms
    resources :instruments
    resources :moods
    resources :sound_types
    resources :regions
    resources :users do
      member do
        post :withdraw
      end
    end
    resources :admin_users
    resources :images
    resources :orders, only: :index
    resources :payments, only: :index
    resources :products do
      member do
        get 'reprocess'
        get 'approve'
        delete 'destroy'
        put 'reject'
        post 'highlight'
        get 'reject_confirm'
      end
    end
    resources :homepage_highlights
    root :to => 'admin#index'
    get 'reprocess_avatars' => 'users#reprocess_avatars'
    get 'become' => 'application#become'
  end

  #resources :multiple_products

  root :to => 'pages#index'

  #  mount Resque::Server.new, :at => "/resque"

  match "*categories" => "categories#index", as: :category

  unless Rails.application.config.consider_all_requests_local
    resources :errors do
      collection do
        get :error_404
        get :error_500
      end
    end
    match '*not_found', :to => 'errors#error_404'
  end
end

ActionDispatch::Routing::Translator.translate_from_file('config/i18n-routes.yml')

app/models/collection.rb
class Collection < ActiveRecord::Base
  extend FriendlyId

  friendly_id :name, use: :slugged

  mount_uploader :cover, AvatarUploader
  mount_uploader :background, BackgroundUploader

  attr_accessible :name, :description, :spotify, :rdio, :itunes, :deezer,
                  :cover, :background, :product_ids

  belongs_to :user
  has_and_belongs_to_many :products

  validates :name, :description, :user, :cover, :product_ids, presence: true

  # Canditate to a form object
  def products_to_form_options
    user.products.order('created_at desc')
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :details]
  layout 'modal', only: [:details]

  def show
    @collection      = Collection.find(params[:id])
    @user            = @collection.user
    @similar_users   = @user.similar_users(4)
    @bought_products = current_user ? current_user.bought_products : []

    @products = @collection.products.is_public.order(:created_at)
    @title_page = params[:products_page] ? "p. #{params[:products_page]}" : ""
    @page_title = "#{t(:page_title_prefix)} #{@user.name} #{@title_page}"

    # Set the breadcrumb
    add_breadcrumb_home
    add_breadcrumb @user.name, user_path(@user)

    @edit_profile = (@user.musician && @user.photo.blank? && @user==current_user) ? true : false

    @purchases_css_class = @user.is_musician? ? '' : 'active'
  end

  def new
    @collection = current_user.collections.new
    # @categories = ancestry_options(Category.scoped.arrange(:order => 'name')) {|i| "#{'-' * i.depth} #{i.name}" }
    # @preset_images = Image.all
  end

  def create
    @collection = current_user.collections.new(params[:collection])

    if @collection.save
      respond_to do |format|
        format.html do
          flash[:notice]= t(:collection_added)
          redirect_to user_path(current_user, anchor: 'collections')
        end

        format.json do
          render :json => @collection
        end
      end
    else
      respond_to do |format|
        format.html do
          # @preset_images = Image.all
          render :new
        end

        format.json do
          render :nothing => true, status: 500
        end
      end
    end
  end

  def edit
    @collection = current_user.collections.find(params[:id])
    # @categories = ancestry_options(Category.scoped.arrange(:order => 'name')) {|i| "#{'-' * i.depth} #{i.name}" }
    # @preset_images = Image.all
    # @sections = Category.menu_sections
  end

  # Update the product information
  def update
    @collection = current_user.collections.find(params[:id])
    # @position = params[:position] if request.xhr?
    # @preset_images = Image.all if request.xhr?
    # @sections = Category.menu_sections

    if @collection.update_attributes(params[:collection])
      respond_to do |format|
        format.html { redirect_to user_path(current_user, anchor: 'collections') }
        format.js { render :action => 'update_success', :layout => false,  :success => "success", :status_code => "200" }
      end
    else
      respond_to do |format|
        format.html do
          # @preset_images = Image.all
          render :action => 'edit'
        end
        format.js { render :action => 'update_error', :layout => false,  :success => "success", :status_code => "200" }
      end
    end
  end

  def destroy
    @collection = current_user.collections.find(params[:id])
    @collection.destroy
    render :json => true
  end

  # Show the user details
  def details
    @collection = Collection.find(params[:collection_id])
  end
end

app/views/collections/_collection.haml
.collection
  = link_to user_collection_path(current_user, collection) do
    = image_tag(collection.cover.thumb.url)

  = link_to collection.name.truncate(22), user_collection_path(current_user, collection)
  |
  = link_to 'Editar', edit_user_collection_path(current_user, collection)

app/views/collections/_form.html.haml
.collection_form
  = simple_form_for @collection, url: [current_user, @collection], :remote => request.xhr? ? true : false, :html => { :rel => 'product-form' } do |f|
    = render :partial => 'layouts/form_error_explanation', :locals => { :model => @collection }

    .clearfix

    .left-inputs
      = f.input :name
      = f.input :description, :as => :text, :input_html => {:rows => 5}
      = f.input :itunes
      = f.input :spotify
      = f.input :rdio
      = f.input :deezer

      - unless request.xhr?
        = f.input :cover, as: :file
        - if @collection.cover.present?
          .thumb
            = image_tag(@collection.cover.thumb.url)

        = f.input :background, as: :file
        - if @collection.background.present?
          .thumb
            = image_tag(@collection.background.thumb.url)

    .right-inputs
      = f.association :products, as: :check_boxes,
        collection: @collection.products_to_form_options,
        wrapper_html: {class: 'products'},
        label: 'Selecione os sons que fazer parte desta coleção'

    .clearfix

    #form-buttons
      = f.button :submit, t(:save), :class => 'btn-vigoo'

app/views/collections/_profile.html.haml
.hero-unit
  .author_image_container
    .new-release-label
      = image_tag 'new_release_label.png'
      %span= t('.new_release')

    .author_image
      = image_tag @collection.cover.url

  .blue_container
    %h1= @collection.name

    .bio_container
      .bio.section-description
        = simple_format(truncate(@collection.description.strip, length: 380, separator: ' '))
        - if @collection.description.strip.size > 380
          .read-more
            = link_to user_collection_details_path(@user, @collection), :class => "support to_modal" do
              = t(:read_more)
              &#9662;

    .stores-links
      - %w(spotify rdio itunes deezer).each do |store|
        - if @collection.public_send(store).present?
          = link_to @collection.public_send(store), class: store, target: '_blank' do
            = image_tag("stores_icons/#{store}.png")

.clear

app/views/collections/details.html.haml
- content_for :modal_header do
  = @collection.name

%p= simple_format @collection.description

app/views/collections/edit.html.haml
%h1.heading= t(:edit_collection)
%h2.heading= @collection.name

= render 'form'

app/views/collections/form.html.haml
= render 'form'

app/views/collections/new.html.haml
%h1.heading= t(:add_collection)
= render 'form'

app/views/collections/show.html.haml
- if @collection.background.present?
  .collection-background{style: "background-image: url(#{@collection.background.url})"}
  .collection-background-fade-white
= render partial: 'profile'

.main-heading-wrapper
  %h1.heading= t(:collection_tracks)
  %h2.heading= t(:find_collection_tracks)

.white-wrapper
  .white-wrapper-shadow

  = render partial: 'users/products', collection: @products, as: :product

  .clearfix

  / %h1.heading
  /   %span.blank= t(:similar_authors)
  / - @similar_users.each do |author|
  /   .grid_3.similar_author.thumb
  /     = render partial: 'users/user_disk', :locals => { :user => author }

  / .clearfix

:javascript
  $(document).ready(function(){
    // my products pagination
    if ($("#products").length>0 && GetURLParameter('products_page')!=undefined){
      $("#product_tab").tab('show');
    }

  });

  $(function(){
    // Function to activate the tab
    function activateTab() {
        var activeTab = $('[href=' + window.location.hash.replace('/', '') + ']');
        activeTab && activeTab.tab('show');
    }

    // Trigger when the page loads
    activateTab();

    // Trigger when the hash changes (forward / back)
    $(window).hashchange(function(e) {
        activateTab();
    });

    // Change hash when a tab changes
    $('a[data-toggle="tab"], a[data-toggle="pill"]').on('shown', function () {
        window.location.hash = '/' + $(this).attr('href').replace('#', '');
    });
  });

app/views/collections/update_error.js.erb
$('#file-form-<%= @position %>').html("<%= escape_javascript(render :partial => 'form') %>");
$("[rel='<%= @position %>']").trigger('click');

app/views/collections/update_success.js.erb
$('#file-form-<%= @position %>').html("<%= escape_javascript(render :partial => 'form') %>");
$("[rel='<%= @position %>'] .file-message").html('editado');
$("#file-forms .loading").hide();

var all_done, possible;
all_done = true;
$(".file-message").each(function(k, v) {
  if ($(v).html()!='editado' && $(v).html()!='erro') {
   all_done = false;
  }
});

if (all_done){
  $("#next-multiple-product").show();
  window.onbeforeunload = null;
}