config/routes.rb
#require 'resque/server'

ORitmo::Application.routes.draw do

  get "accounts/create"
  get "accounts/update"
  get "transactions/create"
  get "payments/index"
  get "payments/confirm"
  get "payments/complete"
  get "termos" => 'pages#termos'
  get "upload" => 'products#upload'
  get "home" => 'pages#index'
  get "about-us" => 'pages#about_us', as: :about_us
  get "faq" => 'pages#faq', as: :faq
  get "sitemap" => 'pages#sitemap'

  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_for :admin_users


  resources :users do
    resources :videos
    resources :products

    resources :collections do
      get 'details'
    end

    get 'details'
    get 'edit_password'

    member do
      get 'edit_photo'
    end

    collection do
      get 'status'
      post 'update_photo'
      put 'update_password'
    end
  end

  get 'users(/:order_by)' => 'users#index'

  get 'set_currency/:currency' => 'users#set_currency', :as => :set_currency

  resources :products do
    get 'form'
    collection do
      get 'upload'
      post 'upload_callback'
    end
    resources :orders
    member do
      get 'create_sample'
      get 'download'
      get 'license'
    end
  end

  resources :seller_terms, :only => [:new,:create]
  resources :buyer_terms, :only => [:new,:create]

  resources :payments do
    member do
      get :confirm
      get :cancel
    end
    collection do
      get :withdraw
      get :exchange_rate
    end
  end

  get 'payments/purchase/:product_id' => 'payments#purchase', :as => :purchase_payment

  namespace :admin do
    resources :categories do
      collection do
        get 'roots'
      end
    end
    resources :rhythms
    resources :instruments
    resources :moods
    resources :sound_types
    resources :regions
    resources :users do
      member do
        post :withdraw
      end
    end
    resources :admin_users
    resources :images
    resources :orders, only: :index
    resources :payments, only: :index
    resources :products do
      member do
        get 'reprocess'
        get 'approve'
        delete 'destroy'
        put 'reject'
        post 'highlight'
        get 'reject_confirm'
      end
    end
    resources :homepage_highlights
    root :to => 'admin#index'
    get 'reprocess_avatars' => 'users#reprocess_avatars'
    get 'become' => 'application#become'
  end

  #resources :multiple_products

  root :to => 'pages#index'

  #  mount Resque::Server.new, :at => "/resque"

  match "*categories" => "categories#index", as: :category

  unless Rails.application.config.consider_all_requests_local
    resources :errors do
      collection do
        get :error_404
        get :error_500
      end
    end
    match '*not_found', :to => 'errors#error_404'
  end
end

ActionDispatch::Routing::Translator.translate_from_file('config/i18n-routes.yml')

app/views/notifier/new_order_confirmation.html.erb
#encoding: utf-8

<p>Fala <%= @order.user.first_name %>!</p>

<p>Sua compra do arquivo <%= @order.product.name %> foi concluída! Estamos ultra-felizes de ter você entre os apoiadores da cultura do remix!</p>

<p>Para fazer o download do seu arquivo clique neste link ou visite sua página de downloads!
<%= link_to @order.product.name, download_product_url(@order.product) %></p>

<p>Qualquer dúvida ou sugestão, não hesite em nos contactar suporte@oritmo.com</p>

<p>Aquele abraço!<br/>
Equipe Oritmo.</p>

== 

<p>Hello <%= @order.user.first_name %>!</p>

<p>Your purchase of the file <%= @order.product.name %> has been completed! 
We're ultra-happy to have you supporting the remix culture!</p>


<p>To download your file, click the link below or visit your profile page.
<%= link_to @order.product.name, download_product_url(@order.product) %></p>

<p>Any doubts or suggestions, don't hesitate to contact us at suporte@oritmo.com</p>

<p>Aquele abraço!<br/>
Oritmo team</p>

app/views/notifier/new_order_received.html.erb
#encoding: utf-8

<p>Vamoooo!!! Mais uma venda, pessoal! O valor foi de R$ <%= @order.amount_paid %> relativa ao som abaixo:</p>

<p><%= @order.product.name %>
by <%= @order.product.user.name %></p>

<p>Comprador: <%= @order.user.name %></p>

app/views/notifier/new_payment_confirmation.html.erb
#encoding: utf-8

<p>Fala <%= @payment.user.first_name %>!</p>

<p>Recebemos seu pagamento no valor de R$ <%= @payment.amount %>. 
Estamos ultra-felizes de ter você entre os apoiadores da cultura do remix!</p>

<p>Qualquer dúvida ou sugestão, não hesite em nos contactar suporte@oritmo.com</p>

<p>Aquele abraço!<br/>
Equipe Oritmo.</p>

==

<p>Hello <%= @payment.user.first_name %>!

<p>We just received your payment in the amount of  R$ <%= @payment.amount %>. 
We're ultra-happy to have you supporting the remix culture!</p>

<p>Any doubts or suggestions, don't hesitate to contact us at suporte@oritmo.com</p>

<p>Aquele abraço!<br/>
Oritmo team</p>

app/views/notifier/new_payment_received.html.erb
#encoding: utf-8

<p>Vamoooo!!! Mais um pagamento, pessoal! O valor foi de R$ <%= @payment.amount %>!</p>

<p>Vamos dar um gás para manter essa vendas altas!</p>

app/views/notifier/new_sale.html.erb
<p>Parabéns, <%= @seller.first_name %>! Você acaba de vender seu som:</p>

<p><%= @order.product.name %> (<%= number_to_currency(@order.product.price) %>)</p>

<p>Comprador: <%= @buyer.first_name %> [<%=  @buyer_location %>]</p>

<p>Com essa venda, seu saldo no Oritmo é de <%= number_to_currency(@seller.account.balance) %>! Para fazer a retirada desse valor você precisa ter um mínimo de R$ 50,00 e precisa estar com sua conta do paypal cadastrada em seu perfil.</p>

<p>Aproveite que você esta bombando e dá aquela vasculhada no seu HD para fazer o upload de mais arquivos e aumentar suas vendas agora mesmo!</p>

<p>Qualquer dúvida ou sugestão, não hesite em nos contactar suporte@oritmo.com</p>

<p>Valeu, parceiro! Aquele abraço!</p>

<p>Equipe Oritmo.</p>

app/views/notifier/new_signup.html.erb
#encoding: utf-8

<p>Olá equipe!</p>

<p>Um novo usuário acaba de se cadastrar! O nome dele é <%=  link_to @user.name, admin_user_path(@user) %> e ele é o usuário <%= @user_count %> cadastrado em nossa plataforma! Vamo que vamo!</p>

app/views/notifier/new_signup_confirmation.html.erb
#encoding: utf-8

<p>Olá <%= @user.first_name %>!</p>

<p>Seja super ultra bem vindo ao Oritmo! Seu cadastro foi realizado com sucesso e você pode atualizá-lo a qualquer momento clicando <%= link_to "aqui", user_path(@user) %>.</p>

<p>Você já pode comprar à vontade ou vender seus arquivos agora mesmo! Não esqueça de confirmar seu email clicando <%= link_to("aqui", confirmation_url(@user, :confirmation_token => @user.confirmation_token)) %></p>

<p>Qualquer dúvida ou sugestão, não hesite em nos contactar suporte@oritmo.com</p>

<p>Aquele abraço!<br/>
Equipe Oritmo.</p>

== 

<p>Hi <%= @user.first_name %>!</p>

<p>Welcome to Oritmo! Your registration was completed successfully and you can update your profile at any time clicking <%= link_to "here", user_path(@user) %>.</p>

<p>You can buy or start selling your sounds immediately! Don forget to confirm your email by clicking <%= link_to("here", confirmation_url(@user, :confirmation_token => @user.confirmation_token)) %></p>

<p>Any doubts or suggestions, don't hesitate to contact suporte@oritmo.com</p>

<p>Aquele abraço!<br/>
Oritmo team.</p>

app/views/notifier/party_invitation.html.erb
#encoding: utf-8

<p>Querido <%= @user.first_name.capitalize %>,</p> 

<p>Chegou a hora de lançar o site "ORITMO - Sons do Brasil para o Mundo". E você, que já faz parte disso tudo, é nosso convidado especial nessa festa. Vai ser neste domingo (05/05), a partir das 18h, no Bar d'Hôtel, na esquina da Delfim Moreira com a Bartolomeu Mitre. Se estiver no Rio de Janeiro você vai nos alegrar com sua presença. Se não estiver, sabemos que estará presente, dentro do espírito de celebração da música brasileira.</p> 
        
<p>Chamamos os Djs Duda M, Jonas Rocha e Ricardo Imperatore para o desafio de criar obras inéditas com os sons de ORITMO. No domingo vamos ver o resultado desse desafio, seguido de muita música e performances ao vivo com Rodrigo Sha e seus convidados especiais. Te esperamos lá!</p>
 
<p>Importante confirmar sua presença no email <a href="mailto:festa@oritmo.com">festa@oritmo.com</a>.</p>

<p>**ORITMO (<a href="http://oritmo.com">oritmo.com</a>) é um marketplace onde os músicos brasileiros criam suas lojas pessoas disponibilizando sons com sua assinatura pessoal para produtores no mundo todo. É toda a riqueza dos ritmos brasileiros como matéria prima de qualidade para Djs, videomakers, compositores de trilhas sonoras e produtores musicais em geral.</p>

<p>Abs.</p>

<%= image_tag('http://oritmo.com/assets/events/festa_lancamento.jpg') %>

app/views/notifier/product_aproved.html.erb
<p>Fala <%= @product.user.first_name %>!</p>

<p>Muitíssimo obrigado pelo cadastro do seu som <i><%= @product.name %></i>!</p>

<p>Já avaliamos o arquivo e ele está liberado para venda no site.</p>

<p>Divulgue seu trabalho pra aumentar suas vendas.</p>

<p>Aquele abraço!<br/>
Equipe Oritmo. </p>

app/views/notifier/product_for_review.html.erb
#encoding: utf-8

<p>Opa, nossa biblioteca de sons acaba de aumentar! O usuário <%= @product.user.name %> acaba de cadastrar o seguinte arquivo:</p>

<p><%= link_to @product.name, admin_product_url(@product.id) %></p>

<p>Mas antes de liberarmos para venda, a equipe de revisão precisa conferir para aprovar ou rejeitar. Se você faz parte da equipe, clique aqui para revisá-los agora mesmo, por favor.
</p>

app/views/notifier/product_rejected.html.erb
<p>Fala <%= @product.user.first_name %>!</p>

<p>Muitíssimo obrigado pelo cadastro do seu som! Infelizmente, <%= @message %></p>

<p>Estamos disponíveis para conversar melhor com você e orientá-lo a conseguir aprovação, basta responder a este email, se desejar.</p>

<p>A sua participação no ORITMO e no movimento da cultura do remix é muito importante! Não desanime com esse nosso email!</p>

<p>Aquele abraço!<br/>
Equipe Oritmo. </p>