config/routes.rb
#require 'resque/server'

ORitmo::Application.routes.draw do

  get "accounts/create"
  get "accounts/update"
  get "transactions/create"
  get "payments/index"
  get "payments/confirm"
  get "payments/complete"
  get "termos" => 'pages#termos'
  get "upload" => 'products#upload'
  get "home" => 'pages#index'
  get "about-us" => 'pages#about_us', as: :about_us
  get "faq" => 'pages#faq', as: :faq
  get "sitemap" => 'pages#sitemap'

  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_for :admin_users


  resources :users do
    resources :videos
    resources :products

    resources :collections do
      get 'details'
    end

    get 'details'
    get 'edit_password'

    member do
      get 'edit_photo'
    end

    collection do
      get 'status'
      post 'update_photo'
      put 'update_password'
    end
  end

  get 'users(/:order_by)' => 'users#index'

  get 'set_currency/:currency' => 'users#set_currency', :as => :set_currency

  resources :products do
    get 'form'
    collection do
      get 'upload'
      post 'upload_callback'
    end
    resources :orders
    member do
      get 'create_sample'
      get 'download'
      get 'license'
    end
  end

  resources :seller_terms, :only => [:new,:create]
  resources :buyer_terms, :only => [:new,:create]

  resources :payments do
    member do
      get :confirm
      get :cancel
    end
    collection do
      get :withdraw
      get :exchange_rate
    end
  end

  get 'payments/purchase/:product_id' => 'payments#purchase', :as => :purchase_payment

  namespace :admin do
    resources :categories do
      collection do
        get 'roots'
      end
    end
    resources :rhythms
    resources :instruments
    resources :moods
    resources :sound_types
    resources :regions
    resources :users do
      member do
        post :withdraw
      end
    end
    resources :admin_users
    resources :images
    resources :orders, only: :index
    resources :payments, only: :index
    resources :products do
      member do
        get 'reprocess'
        get 'approve'
        delete 'destroy'
        put 'reject'
        post 'highlight'
        get 'reject_confirm'
      end
    end
    resources :homepage_highlights
    root :to => 'admin#index'
    get 'reprocess_avatars' => 'users#reprocess_avatars'
    get 'become' => 'application#become'
  end

  #resources :multiple_products

  root :to => 'pages#index'

  #  mount Resque::Server.new, :at => "/resque"

  match "*categories" => "categories#index", as: :category

  unless Rails.application.config.consider_all_requests_local
    resources :errors do
      collection do
        get :error_404
        get :error_500
      end
    end
    match '*not_found', :to => 'errors#error_404'
  end
end

ActionDispatch::Routing::Translator.translate_from_file('config/i18n-routes.yml')

app/models/image.rb
class Image < ActiveRecord::Base
  # attr_accessible :title, :body
  
  acts_as_paranoid
  mount_uploader :photo, PhotoUploader
  attr_accessible :name, :photo
  
  validates :photo, :presence => true
  
  has_many :products
  
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::ApplicationController

  def index
    @images = Image.all
  end
  
  def new
    @image = Image.new
  end
  
  def create
    @image = Image.new(params[:image])
  
    if @image.save
      flash[:notice]="Image added"
      redirect_to send("admin_images_path") 
    else
      render :new
    end
  end
  
  def edit
    @image = Image.find(params[:id])
  end
  
  def update
    @image = Image.find(params[:id])
    result = @image.update_attributes(params[:image])
      
    respond_to do |format|
      format.html do
        if result
          redirect_to admin_images_path
        else
          render :action => 'edit'
        end
      end
    end
  end
  
  def destroy
    @image = Image.find(params[:id])
    if @image.destroy
      redirect_to send("admin_images_path") 
    end
  end
  
end

app/views/admin/images/_form.html.haml
=simple_form_for [:admin, @image] do |f|
  = f.input :name
  = f.input :photo, :as => :file
  - if !@image.photo.blank?
    = image_tag(@image.photo.url(:thumb))
    %br
    %br
  .clearfix
  = f.button :submit, class: 'btn btn-primary'
  = link_to "Cancel", :back

app/views/admin/images/edit.html.haml
=render partial: 'form'

app/views/admin/images/index.html.haml
.page-header
  %h1 Images
  
%p= link_to "Add image", new_admin_image_path, class: 'btn btn-primary'

- @images.in_groups_of(4).each do |group|
  .row12.clearfix.admin-image-row
    - group.each do |image|
      - unless image.nil?
        .span3.preset-image-container{:rel => image.id}
          = link_to edit_admin_image_path(image) do
            = image_tag image.photo.url(:thumb), class: 'admin-image-tag'
          = link_to admin_image_path(image), :method => :delete, :confirm => 'Are you sure?', class: 'btn btn-danger btn-mini delete-image-button', :id => "delete_#{image.id}" do
            %i.icon-remove.icon-white

app/views/admin/images/new.html.haml
=render partial: 'form'