config/routes.rb
#require 'resque/server'

ORitmo::Application.routes.draw do

  get "accounts/create"
  get "accounts/update"
  get "transactions/create"
  get "payments/index"
  get "payments/confirm"
  get "payments/complete"
  get "termos" => 'pages#termos'
  get "upload" => 'products#upload'
  get "home" => 'pages#index'
  get "about-us" => 'pages#about_us', as: :about_us
  get "faq" => 'pages#faq', as: :faq
  get "sitemap" => 'pages#sitemap'

  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_for :admin_users


  resources :users do
    resources :videos
    resources :products

    resources :collections do
      get 'details'
    end

    get 'details'
    get 'edit_password'

    member do
      get 'edit_photo'
    end

    collection do
      get 'status'
      post 'update_photo'
      put 'update_password'
    end
  end

  get 'users(/:order_by)' => 'users#index'

  get 'set_currency/:currency' => 'users#set_currency', :as => :set_currency

  resources :products do
    get 'form'
    collection do
      get 'upload'
      post 'upload_callback'
    end
    resources :orders
    member do
      get 'create_sample'
      get 'download'
      get 'license'
    end
  end

  resources :seller_terms, :only => [:new,:create]
  resources :buyer_terms, :only => [:new,:create]

  resources :payments do
    member do
      get :confirm
      get :cancel
    end
    collection do
      get :withdraw
      get :exchange_rate
    end
  end

  get 'payments/purchase/:product_id' => 'payments#purchase', :as => :purchase_payment

  namespace :admin do
    resources :categories do
      collection do
        get 'roots'
      end
    end
    resources :rhythms
    resources :instruments
    resources :moods
    resources :sound_types
    resources :regions
    resources :users do
      member do
        post :withdraw
      end
    end
    resources :admin_users
    resources :images
    resources :orders, only: :index
    resources :payments, only: :index
    resources :products do
      member do
        get 'reprocess'
        get 'approve'
        delete 'destroy'
        put 'reject'
        post 'highlight'
        get 'reject_confirm'
      end
    end
    resources :homepage_highlights
    root :to => 'admin#index'
    get 'reprocess_avatars' => 'users#reprocess_avatars'
    get 'become' => 'application#become'
  end

  #resources :multiple_products

  root :to => 'pages#index'

  #  mount Resque::Server.new, :at => "/resque"

  match "*categories" => "categories#index", as: :category

  unless Rails.application.config.consider_all_requests_local
    resources :errors do
      collection do
        get :error_404
        get :error_500
      end
    end
    match '*not_found', :to => 'errors#error_404'
  end
end

ActionDispatch::Routing::Translator.translate_from_file('config/i18n-routes.yml')

app/models/category.rb
class Category < ActiveRecord::Base
  
  extend FriendlyId
  
  # Attributes
  attr_accessible :name, :description, :parent_id, :file, :status, :sort_by, :type, 
                  :photo, :remove_photo, :background, :remove_background, :product_count

  # Associations
  has_ancestry
  has_and_belongs_to_many :products
  has_and_belongs_to_many :users
  
  # Validations
  validates :name, :presence => true
  
  mount_uploader :photo, CategoryPhotoUploader
  mount_uploader :background, BackgroundUploader
  
  # Others
  translates :name, :slug
  friendly_id :name, use: :globalize
  
  scope :active, where("exists (select 1 from categories_products cp join products p on cp.product_id = p.id where cp.category_id = categories.id and p.status='active')")
  
  # Methods

  # Find all public products
  def public_products
    self.products.is_public
  end
  
  # Find all instruments and sort by name
  def self.all_instruments
    Category.first.children.all :order => "name asc"
  end

  def self.build_hash
    @hash ||= self.full_hash
  end
  
  def self.full_hash
    lehash = Hash.new 
    Category.roots.arrange(:order => :sort_by).to_a.flatten.delete_if(&:blank?).each do |c|
      lehash[c.name] ||= c.children
    end
    lehash
  end
  
  def update_product_count
    self.update_attributes(:product_count => self.products.is_public.length)
  end
  
  def self.menu_sections
    self.roots.arrange(:order => :sort_by).to_a.flatten.delete_if(&:blank?)
  end
  
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  helper_method :model, :model_name
  
  def index
    @categories = model.order(:name)
  end
  
  def roots
    @categories = Category.roots
  end
  
  def new
    @category = model.new(:parent_id => params[:parent_id])
  end
  
  def create
    @category = model.new(params[model_name])
  
    if @category.save
      flash[:notice]="#{model_name} added"
      redirect_to send("admin_#{model_name.downcase.pluralize}_path") 
    else
      render :new
    end
    
  end
  
  def edit
    @category = model.find(params[:id])
  end
  
  def update
    @category = model.find(params[:id])
    if @category.update_attributes(params[model_name])
      respond_to do |format|
        format.html do
          redirect_to send("admin_#{model_name.downcase.pluralize}_path") 
        end
        format.js do
          render :nothing => true
        end
      end
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @category = model.find(params[:id])
    if @category.destroy
      redirect_to send("admin_#{model_name.downcase.pluralize}_path") 
    end
  end
  
  
  private 
  def model
    @model ||= controller_name.classify.constantize
  end
  
  def model_name
    @model_name ||= controller_name.singularize
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # List the children elements of father element
  
  #caches_page :all
  
  def index
    @category = category
    @children = @category.children.
      order('product_count desc').
      page(params[:page])
      
    @title_page = params[:page] ? "p. #{params[:page]}" : ""
    if @children.size == 0
      @page_title = "#{t(:page_title_prefix)} #{@category.parent.name} - #{@category.name} #{@title_page}"
      show
      render :show 
    else
      @category_name = @category.name==t(:region).capitalize ? t(:regions) : @category.name.pluralize
      @page_title = "#{t(:page_title_prefix)} #{@category_name.capitalize}"
    end
  end

  def show
    @category = category #Category.find(params[:id])
    @sort_by = params[:sort_by] || :created_at
    @products = @category.products.is_public.order(@sort_by).paginate(page: params[:page], per_page: 24)
    @top_authors = User.where("exists (\
      select 1 from products a \
      join categories_products b on a.id = b.product_id \
      where a.user_id = users.id \
      and a.status=\'active\' \
      and b.category_id=#{@category.id}) \
      ").order('internal_rating desc')[0..3]
  end
  
  protected
  
    def category
      @category ||= Category.find(slug) 
    end
  
    def slug
      @slug ||= params[:categories].split('/').last.gsub(".json", "")
    end
  
end

app/helpers/admin/categories_helper.rb
module Admin
  module CategoriesHelper
    def nested_categories(category)
      content_tag(:ul) do
        content_tag(:li) do
          concat category.name 
          html = " [#{link_to "Add", Rails.application.routes.url_helpers.new_admin_category_path(:parent_id => category.id)}]"
          html += "<ul>"
          if category.children.present?
            category.children.sort_by(&:name).each do |subcategory|
              html += content_tag(:li) do
                concat link_to subcategory.name, edit_admin_category_path(subcategory)
                concat ' '
                concat link_to 'x', admin_category_path(subcategory), method: :delete, confirm: 'Are you sure?'
                # concat subcategory.name
              end
            end
          end
          html += "</ul>"
          concat html.html_safe
        end  
      end
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  # List the elements in check box elements format
  def categories_check_box_list(elements, model, field_name)
    total = elements.size
    cols = 3
    lines = (total / cols).ceil

    content = ""
    col = ""

    i = 0
    for e in elements
      class_name = model.class.to_s.underscore
      e_id = "#{class_name}_#{field_name}_#{e.id}"
      input = check_box_tag("#{class_name}[#{field_name}][]", e.id, model.categories.include?(e) ? true : false, :id => e_id)
      label = label_tag(e_id, e.name)

      span = content_tag(:span, (input + label), :class => "checkbox").html_safe
      # p span
      col += content_tag(:div, span, :class => "table-cell").html_safe
      i += 1

      if i == lines
        content += content_tag(:div, col.html_safe, :class => "table-col").html_safe
        i = 0
        col = ""
      end
    end

    content_tag(:div, (content + content_tag(:div, "", :class => "clear")).html_safe, :class => "table-list")
  end

  # Format the category name with the number of products elements
  def category_name_for_list(category)
    "#{category.name} (#{category.product_count})"
  end

  def regions_for_user(user)
    #city = Category.where(name: user.city).first
    #link_to user.city, category_path(city), class: "support"
  end
end

app/views/categories/_category.html.haml
%li #{category.name} #{link_to "+", new_category_path(:parent_id => category)}

app/views/categories/all.html.haml
%h1.heading= @category.name
%h2.heading= t(:slogan_category_children, :category_name => @category.name)

- for child in @children
  = link_to category_path(child) do
    .grid_4
      .category_box
        - if !child.photo.blank?
          - cat_class = "compact"
          .category_photo
            = image_tag child.photo.url(:thumb)
        .category_name{class: cat_class}
          %span.name= child.name
          %br
          %span.sounds= "(#{child.product_count} #{t(:sound, :count => child.product_count)})"
        .arrow
          %i.icon-chevron-right.icon-blue
.clearfix
= will_paginate @children

app/views/categories/index.html.haml
%h1.heading= @category_name.pluralize
%h2.heading= t(:slogan_category_children, :category_name => @category_name.downcase)

- for child in @children
  = link_to category_path(child) do
    .grid_4
      .category_box
        - if !child.photo.blank?
          - cat_class = "compact"
          .category_photo
            = image_tag child.photo.url(:thumb)
        .category_name{class: cat_class}
          %span.name= child.name
          %br
          %span.sounds= "(#{child.product_count} #{t(:sound, :count => child.product_count)})"
        .arrow
          %i.icon-chevron-right.icon-blue
.clearfix
= will_paginate @children

app/views/categories/new.html.haml
=simple_form_for @category do |f|
  = f.input :name
  = f.hidden_field :parent_id
  = f.button :submit
  = link_to "Cancel", :back

app/views/categories/show.html.haml
- if !@category.background.blank?
  - content_for :section_head do
    .row-fluid
      %div
        =image_tag @category.background.url, class: 'category_header_image'
        .pattern &nbsp;

  .row_12.category_hero

    .grid_6
      %h1= @category.name
      .grid_3.alpha.category_description.description.section-description
        = truncate( @category.description, :length => 450, :separator => ' ' )
      
      .grid_3.omega.category_description
        - case @category.class.name
          - when t(:rhythm).capitalize
            %h2.section-subtitle= t(:region)
            .section-description= @category.regions.map { |cat| link_to cat.name, category_path(cat.slug) }.join(", ").html_safe
      
            %h2.section-subtitle= t(:instruments).pluralize
            .section-description= @category.instruments.map { |cat| link_to cat.name, category_path(cat.slug) }.join(", ").html_safe
              
          - when t(:instrument).capitalize
            %h2.section-subtitle= t(:rhythm).pluralize
            .section-description= @category.rhythms.map { |cat| link_to cat.name, category_path(cat.slug) }.join(", ").html_safe
    
    .grid_6
      .category_image_container
        .category_image
          - if !@category.photo.blank?
            = image_tag @category.photo.url
          
  .clearfix        

.category_body
  %h1.heading= @category.name
  %h2.heading= "Todos os sons em #{@category.name}"

  = render partial: 'layouts/products_ordering', locals: { url: category_path(@category) }

  - if @products.size > 0
    - @products.in_groups_of(4).each do |group|
      .row_12.category_product_group
        - group.each do |product|
          = render partial: 'layouts/product', :locals => { :product => product, :type => @category, :section =>"category" } unless product.nil?
        .clearfix
    .clearfix
    = will_paginate @products
    
    
    %h1.heading
      %span.blank= t(:authors)
    %h2.heading= "Artistas em #{@category.name}"
    - @top_authors.each do |author|
      .grid_3.similar_author.thumb
        = render partial: 'users/user_disk', :locals => { :user => author }
    
    
  - else
    .alert.alert-error= t(:no_products_found)

  .clearfix
.clearfix